import type { Metadata } from "next";
import "./styles/reset.css";
import "./styles/globals.css";
import "./styles/output.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white dark:bg-secondary-000`}>{children}</body>
    </html>
  );
}
